version: 2.0

# Inspired by:
# https://github.com/CircleCI-Public/circleci-demo-workflows/blob/workspace-forwarding/.circleci/config.yml
# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
#
# For list of official CircleCI node.js images, go to:
# https://hub.docker.com/r/circleci/node/tags/

jobs:
  test-jasmine:
    docker:
      # need '-browsers' version to test in real (xvfb-wrapped) browsers
      - image: circleci/node:10.9.0-browsers
    parallelism: 4
    working_directory: ~/plotly.js
    steps:
      - checkout
      - attach_workspace:
          at: ~/plotly.js
      - run:
          name: Run jasmine tests
          command: |
            echo $(circleci tests glob "test/jasmine/tests/*")
            circleci tests glob "test/jasmine/tests/*" | xargs -n 1 echo


workflows:
  version: 2
  build-and-test:
    jobs:
      - test-jasmine
